name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read

    env:
      POETRY_DYNAMIC_VERSIONING_ENABLE: true
      POETRY_DYNAMIC_VERSIONING_COMMANDS: "build,publish,version"
      POETRY_DYNAMIC_VERSIONING_METADATA: true

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: "pip"

    - name: Install dependencies
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry poetry-dynamic-versioning[plugin] build twine
        poetry install --with dev,docs

    - name: Check version
      run: |
        poetry version
        poetry run python -c "import pypackage_template; print(pypackage_template.__version__)"

    - name: Build package
      run: poetry build

    - name: Check distribution
      run: |
        poetry run twine check dist/*

    - name: Build wheels for multiple platforms
      uses: pypa/cibuildwheel@v2.16.2
      env:
        CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
        CIBW_ARCHS_LINUX: "x86_64 aarch64"
        CIBW_ARCHS_MACOS: "x86_64 arm64"
        CIBW_ARCHS_WINDOWS: "AMD64 ARM64"
        CIBW_TEST_COMMAND: "pytest {project}/tests"
        CIBW_TEST_REQUIRES: "pytest"

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          wheelhouse/*.whl
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist/*
          wheelhouse/*.whl
